### ISSUE TITLE
Tự học ISTQB 

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2017#128]
## 1. Việc cá nhân:
Do thứ 2 tới là 20/11, được nghỉ, nên tất cả các em đăng ký và học thêm khóa học này về ISTQB: https://www.udemy.com/istqb-certified-tester-foundation-level-ctfl-preparation-exam-review/, là các kiến thức cơ bản về kiểm thử. Yêu cầu tất cả hoàn thành khóa học nghiêm túc và làm đầy đủ bài tập, quiz, chụp ảnh màn hình kết quả khóa học nộp trên github. 

Chú ý chụp toàn bộ màn hình bằng tiện ích, ví dụ: https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl. 
Nộp vào thư mục istqb ở gốc của repo này, nhưng tạo pull request nộp kết quả theo nhóm.

Hạn hoàn thành: 4/12/2017.

## 2. Việc cho các nhóm:
Do không đủ câu trên khóa học nên các nhóm lần lượt nhập các câu ở [đây ](https://www.dropbox.com/s/16p1fd3fjefnfx2/quiz.zip?dl=0) vào sheet ISTQB để luyện/kiểm tra trên phần mềm sau. Thứ tự các nhóm đã ghi rõ trong sheet SV - Nhóm.
https://docs.google.com/spreadsheets/d/1SRUjhmj-8TLGdvhBpk_-BBZETcQx-8is1PxWL171Wd0/edit#gid=1158584517

Hạn hoàn thành: 30/11/2017.

**Comment by thanhminhmr** [comment]
Em thưa thầy, em dùng Firefox thì có thể sử dụng Firefox Screenshots không ạ?

**Comment by truonganhhoang** [comment]
Em tìm phần mở rộng cho firefox nhé, ví dụ: https://screenshots.firefox.com/
