### ISSUE TITLE
Bài tập nhóm tuần 9

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2017#73]
Mỗi nhóm chọn một công cụ trong các công cụ sau để trình bày trên lớp vào tuần 10 (ngày 30/10/2017)
https://github.com/atinfo/awesome-test-automation/blob/master/automation-and-testing-as-service.md

Các nhóm không chọn trùng nhau, nên nhóm nào chọn trước thì đăng ký bằng cách comment vào issue này đồng thời đưa tên và link công cụ vào link dưới đây, sheet [SV-Nhóm], phần từ ô H86.

https://docs.google.com/spreadsheets/d/1SRUjhmj-8TLGdvhBpk_-BBZETcQx-8is1PxWL171Wd0/edit#gid=0

**Comment by tuanhnt1712** [comment]
Nhóm AHT chọn công cụ BlazeMeter
link: https://www.blazemeter.com/

**Comment by MyTraDo** [comment]
Nhóm DOA chọn công cụ Mailosaur
link: [https://mailosaur.com/](url)

**Comment by thanhminhmr** [comment]
Nhóm FOX chọn công cụ: BrowserShots
http://browsershots.org/

**Comment by minhth1905** [comment]
Nhóm QTM chọn công cụ: TestAnywhere
link: https://testanywhere.co/

**Comment by duong110397** [comment]
Nhóm M chọn công cụ: Browserstack
link: https://www.browserstack.com/

**Comment by uongvan09** [comment]
Nhóm MID chọn công cụ: CrossBrowserTesting
link: https://crossbrowsertesting.com/

**Comment by uongvan09** [comment]
Nhóm MID chọn công cụ: backTrac
link: https://backtrac.io/

**Comment by conghieutlvy** [comment]
Nhóm TriH chọn công cụ: Crossbrowsertesting
Link: https://crossbrowsertesting.com

**Comment by phungphuong** [comment]
Nhóm BIs chọn công cụ: Loader.io
link: https://loader.io/

**Comment by Lanuet** [comment]
Nhóm BUG chọn công cụ: Assertible
Link: [https://assertible.com/](url)

**Comment by nguyenducthuanuet** [comment]
Nhóm 3T chọn công cụ: Sitespeed
Link: [Sitespeed](https://www.sitespeed.io/)

**Comment by vuhoanglinh96** [comment]
Nhóm aloha chọn công cụ: Scan My Server
Link: https://www.scanmyserver.com/

**Comment by ChuThom610** [comment]
Nhóm DTT chọn công cụ: SauceLabs
Link: https://saucelabs.com/

**Comment by viethoanguyen97** [comment]
Nhóm NHN chọn công cụ: Load Impact
Link: https://loadimpact.com/

**Comment by hahien196** [comment]
Nhóm M2H chọn công cụ: Hive CI
Link http://bbc.github.io/hive-ci/

*Trân trọng!*
*Hà Thị Hiện*
Tel: *(+84) 1679859271*
Skype/Email: hien196tb@gmail.com


2017-10-25 9:19 GMT+07:00 ChuThom610 <notifications@github.com>:

**Comment by CreativeSelf8** [comment]
Nhóm NOOBS chọn công cụ : AppliTools
Link : https://applitools.com/

2017-10-25 12:46 GMT+07:00 hienht <notifications@github.com>:

**Comment by haileebn** [comment]
Nhóm GGWP chọn công cụ: Netcraft
https://www.netcraft.com/security-testing/web-application/

**Comment by nartoan** [comment]
Nhóm **nrop** chọn  [_Selenium_](http://www.seleniumhq.org/)

**Comment by theonehg** [comment]
Nhóm HAH chọn WebSecurify 
https://www.websecurify.com/

**Comment by VanLuong1996** [comment]
Nhóm QA chọn Mailosaur 
https://mailosaur.com/

**Comment by hieusonson9x** [comment]
Nhóm Dev's Nightmare chọn TestNG
http://testng.org

**Comment by truonganhhoang** [comment]
Các nhóm làm video giới thiệu về công cụ kiểm thử mình tìm hiểu và đưa link youtube vào readme.md của repo này. Hạn nộp là tuần tới 5/11/2017.

**Comment by hieunt94** [comment]
Nhóm Hello chọn Blitz
https://www.blitz.io/

**Comment by xuanuet** [comment]
Nhóm NoMore chon Hackertarget
https://hackertarget.com

**Comment by ngocnhu123** [comment]
Nhóm HMN chọn katalon studio
